# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-XSLT
version:      1.2
version_from: XSLT.pm
installdirs:  site
requires:
    Template:                      0
    XML::LibXSLT:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
